FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY pom.xml ./
COPY mvnw ./
COPY .mvn .mvn

RUN ./mvnw dependency:resolve

COPY . .

RUN ./mvnw clean package -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "target/agent-module-0.0.1-SNAPSHOT.jar"]
